grep -n '<td' samples/out-0.txt
grep -n '\[\[[^|]*\|[^\]]*\]\]' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n 'text-align' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n 'math>' ../../data/wikipedia-corpus/out-0.raw.txt 
grep -n 'ref>' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n 'references>' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n 'poem>' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n 'syntaxhighlight>' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n '<math' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n '<ref' ../../data/wikipedia-corpus/out-0.raw.txt      
grep -n '<syntaxhighlight' ../../data/wikipedia-corpus/out-0.raw.txt
grep -n '<poem' ../../data/wikipedia-corpus/out-0.raw.txt
