grep -n '<td' $1
grep -n '\[\[[^|]*\|[^\]]*\]\]' $1
grep -n 'text-align' $1
grep -n 'math>' $1 
grep -n 'ref>' $1
grep -n 'references>' $1
grep -n 'poem>' $1
grep -n 'syntaxhighlight>' $1
grep -n '<math' $1
grep -n '<ref' $1      
grep -n '<syntaxhighlight' $1
grep -n '<poem' $1
grep -n '\\begin' $1
grep -n '\\frac' $1
grep -n '\\left' $1
grep -n '\]\]' $1
grep -n '\[\[' $1
grep -n '\]\}' $1
grep -n '\[{' $1
grep -n '\{\[' $1
grep -n '\]\]' $1
grep -n '\{{' $1
grep -n '\}\}' $1
grep -n '\[[a-zA-Z0-9]*\]' $1
grep -n '<[a-zA-Z0-9]*>' $1
grep -n '</[a-zA-Z0-9]*>' $1

