./files0.sh > /dev/null &
./files1.sh > /dev/null &
./files2.sh > /dev/null &
./files3.sh > /dev/null &
./files4.sh > /dev/null &
./files5.sh > /dev/null &
./files6.sh > /dev/null &
./files7.sh > /dev/null &
./files8.sh > /dev/null &
./files9.sh > /dev/null &
./files10.sh > /dev/null &
./files11.sh > /dev/null &
./files12.sh > /dev/null &
./files13.sh > /dev/null &
./files14.sh > /dev/null &
./files15.sh > /dev/null &
./files16.sh > /dev/null &
./files17.sh > /dev/null &
./files18.sh > /dev/null &
./files19.sh > /dev/null &
./files20.sh > /dev/null &
./files21.sh > /dev/null &
./files22.sh > /dev/null &
./files23.sh > /dev/null &
./files24.sh > /dev/null &
./files25.sh > /dev/null &
./files26.sh > /dev/null &
./files27.sh > /dev/null &
./files28.sh > /dev/null &
./files29.sh > /dev/null &
./files30.sh > /dev/null &
./files31.sh > /dev/null &
./files32.sh > /dev/null &
./files33.sh > /dev/null &
./files34.sh > /dev/null &
./files35.sh > /dev/null &
./files36.sh > /dev/null &
./files37.sh > /dev/null &
./files38.sh > /dev/null &
./files39.sh > /dev/null &

